name: "yolov5s_trt"
platform: "tensorrt_plan"
max_batch_size: 1
input [
    {
        name: "input"
        data_type: TYPE_FP32
        format: FORMAT_NCHW
        dims: [3, 384, 640]
    }
]
output [
    {
        name: "output"
        data_type: TYPE_FP32
        dims: [15120, 85]
        label_filename: "coco.txt"
    }
]
