name: "preprocess"
backend: "python"
max_batch_size: 256 
input [
{
    name: "INPUT_0"
    data_type: TYPE_UINT8
    dims: [3, 384, 640]
}
]
 
output [
{
    name: "OUTPUT_0"
    data_type: TYPE_FP32
    dims: [3, 384, 640]
}
]

instance_group [{ kind: KIND_CPU }]