name: "yolov5s_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 1
input [
    {
        name: "onnx::Cast_0"
        data_type: TYPE_FP32
        format: FORMAT_NCHW
        dims: [3, 384, 640]
    }
]
output [
    {
        name: "444"
        data_type: TYPE_FP32
        dims: [1, 15120, 85]
        label_filename: "coco.txt"
    }
]
